### ISSUE TITLE
A.18.33    spelling of shorthand

### ISSUE THREAD

**Issue by JohnGPBarnes** [pat-rogers/Ada-202x-WG9-Informal-Review#127]
A.18.33		24/3

	shorthand is normally one word these days. By far the majority of uses of shorthand in the AARM are one word. There are some instances of short-hand which reminds me that in the old days we said to-day and to-morrow.

**Comment by ARG-Editor** [comment]
OK. This will be handled in the presentation AI for this review, AI12-0426-1. I included changing the two AARM notes (3.8(15.a) and 11.1(1.c)) that use "short-hand". The AARM will at least be consistent about one thing. - Editor.
