### ISSUE TITLE
5.6.1(4/5) and others, example not preceded by our usual "Example of ..." lead in

### ISSUE THREAD

**Issue by pat-rogers** [pat-rogers/Ada-202x-WG9-Informal-Review#7]
Originator: Tucker Taft (via ARG list)

Paragraph: 5.6.1(4/5), 5.5.3(30/5), 5.5.3(34/5), 6.3(8)

The example in section 5.6.1 (Parallel Block Statements) is not preceded by
our usual "Example of ..." lead in.  

In RM 6.3, we have "Example of procedure body:" and "Example of a function
body:" in the same set of examples.  It would seem we should add "a" to the
first lead in. [Editor's notes: Tucker had the wrong subclause reference -
he probably got it from the bottom of the page, which shows the *last*
subclause on a page. No idea why Word does that. Anyway, this has been true
since Ada 9x - it's in the Sept 1993 edition. Must be important. ;-)]

In RM 5.5.3 (Procedural Iterators) the lead ins to the examples are not
italicized (paragraphs 30/5 and 34/5).

In RM 5.5.2 (Generalized Loop Iteration) the example lead in is unlike most
others.  It is a comment in the same font size as the example.  Normally the
lead in is larger, italicized, and starts with "Example[s] of ...".

**Comment by pat-rogers** [comment]
Editor's reply: 

This is the first I know of this lead-in being "usual". You're implying that
all examples should be constructed that way, but I don't know of many (if
any) modern examples (Ada 2012 or later) that are. Certainly, no one has
been looking for that when examples were created and added to the RM.

For instance, 3.2.4 has a lead-in only for the large example, and not for
the smaller ones that start the grouping. 4.5.10 has a heading, but they
aren't described as examples (No "example of"), same with 4.5.8 and 4.5.9.
4.5.7 has no heading at all. That's just from a few probes into clauses that
I know are relatively new.

Suggested fix: Tucker will check the lead-ins for all of the examples in the
RM, and suggest changes as needed.

**Comment by ARG-Editor** [comment]
#97 is the response to "Tucker will check", and it is much more detailed than this one, so this one is marked duplicated and closed.
